- Transcendence/TransCore/RPGCode.xml
This changes rpgInstallDevicePrep so that replacing devices uses the same rules as installing them. So if the player is the installer and no tech criteria or max levels are specified, they can remove anything.
Also some minor language improvements.
https://ministry.kronosaur.com/record.hexm?id=84089
> Fix inability to replace devices with auton bay

- Transcendence/Transcendence/CDeviceCounterDisplay.cpp
Previously, a negative charge on the right-most device would draw on top
of the charge for the device immediately to the left.
> Fix drawing of capacitor counters when 2+ devices are charging.

- Mammoth/Include/TSEDeviceClassesImpl.h
- Mammoth/Include/TSEDevices.h
- Mammoth/TSE/CInstalledDevice.cpp
- Mammoth/TSE/CWeaponClass.cpp
This allows repeating weapons to track targets during the burst,
rather than being stuck in the same firing angle for the entire burst.
Without this attribute, the repeating weapon functions as it usually does.
> Added 'burstTracksTargets' attribute for repeating weapons (port #70 from original Mammoth repo).

- Mammoth/TSE/C3DConversion.cpp
Previously the compatibility mode was switched on when Z was specified,
rather than the reverse.
> Fix 3DConversion + ZPos.

- Mammoth/Include/TSEDevices.h
- Mammoth/Include/TSEVersions.h
- Mammoth/TSE/CCExtensions.cpp
- Mammoth/TSE/CDeviceTable.cpp
- Mammoth/TSE/CInstalledDevice.cpp
- Mammoth/TSE/CWeaponClass.cpp
- Mammoth/TSE/Devices.cpp
See http://ministry.kronosaur.com/record.hexm?id=84395 for a discussion.
This can obviously wait after 1.8 release :).
Here are some more of my thoughts about the implementation strategy. I ended up scaling everything, and not just the perpendicular direction because I think the in-universe explanation for this factor is that it is a display correction, not an actual property of the weapon. I.e. the item graphics display the weapons as dual-barrel etc assemblies with a fixed separation, so what this approximates is that the same weapon appears smaller (and thus has closer-spaced shots) on certain ships. Custom configurations to me represent some custom variety of that, and thus are scaled uniformly as well.
> Implement configurable shot separation scale.

- Mammoth/TSE/CCExtensions.cpp
`itmSetProperty` will always give "Insufficient arguments" when run due to an improperly placed comma. I've relocated the comma to the correct location (after the help string).
> Fixed 'Insufficient arguments' error with itmSetProperty.

- Mammoth/Include/TSEDeviceClassesImpl.h
- Mammoth/TSE/CWeaponClass.cpp
This attribute prevents firing the specified weapon when blinded e.g. by a blinder cannon or damaged visual display ROM. This could be used to give blinding weapons some use against AI ships, by preventing the AI ships (and the player) from using certain weapons (e.g. homing missiles) if blinded.
> Added NoFireWhileBlind property to weapons (port of #65 from old Mammoth codebase)

- Mammoth/Include/TSEDevices.h
- Mammoth/Include/TSEShipSystems.h
- Mammoth/Include/TSESpaceObjectsImpl.h
- Mammoth/TSE/CCExtensions.cpp
- Mammoth/TSE/CDeviceSystem.cpp
- Mammoth/TSE/CInstalledDevice.cpp
- Mammoth/TSE/CItem.cpp
- Mammoth/TSE/CShip.cpp
- Mammoth/TSE/CWeaponClass.cpp
- Mammoth/TSE/Devices.cpp
- Mammoth/TSUI/CWeaponHUDCircular.cpp
- Mammoth/TSUI/CWeaponHUDDefault.cpp
- Transcendence/Transcendence/PlayerController.cpp
The new linked fire option `"whenSelected"` allows installing multiple weapons of the same type on a (player) ship, then selecting them all as one weapon. For example, if we have 3 laser cannons and a SmartCannon on the player ship, and all of the lasers have the `"whenSelected"` linked fire option, cycling through the guns with "W" will give us 2 options: "laser cannon" (which selects the 3 lasers) and "SmartCannon" (which selects the SmartCannon).
I've included an example of this in action at https://gfycat.com/RevolvingMinorIcelandicsheepdog. The player ship in this case has: 3 light ion blasters, 2 positron lancers, and 2 Akan 30 cannons all with `linkedFireOptions='whenSelected'`. There is also a (single) dual laser cannon installed, which does not have `"whenSelected"` (or any other …
> Added new linked fire options: "whenSelected", "whenSelectedSameVariant" and "neverFire"

- Mammoth/Include/TSEDeviceClassesImpl.h
- Mammoth/Include/TSEDevices.h
- Mammoth/Include/TSEShipSystems.h
- Mammoth/Include/TSESpaceObjectsImpl.h
- Mammoth/TSE/CDeviceSystem.cpp
- Mammoth/TSE/CShip.cpp
- Mammoth/TSE/CWeaponClass.cpp
This pull request enables player ships with multiple launchers installed to cycle through all available launchers when the Tab key is pressed. Tab will now cycle through all available missiles, for all available launchers, instead of only the missiles for one launcher.
As with before, the Tab key selects the next missile for the current launcher, and functions identically if only one launcher is installed. However, if multiple launchers are installed, then when the last missile for the current launcher is selected, Tab will instead select the first missile for the next launcher.
> Added multiple launcher support to player ships.

- Mammoth/Include/TSE.h
- Mammoth/Include/TSEDevices.h
- Mammoth/Include/TSEShipAI.h
- Mammoth/Include/TSESpaceObjectsEnum.h
- Mammoth/Include/TSESpaceObjectsImpl.h
- Mammoth/Include/TSEWeaponFireDesc.h
- Mammoth/TSE/CBaseShipAI.cpp
- Mammoth/TSE/CInstalledDevice.cpp
- Mammoth/TSE/CMissile.cpp
- Mammoth/TSE/CShip.cpp
- Mammoth/TSE/CSpaceObject.cpp
- Mammoth/TSE/CWeaponFireDesc.cpp
- Mammoth/TSE/Devices.cpp
- Mammoth/TSE/ShipAIImpl.h
- Transcendence/Transcendence/IntroSession.h
- Transcendence/Transcendence/PlayerController.cpp
- Transcendence/Transcendence/PlayerShip.h
This change adds a new property for weapons: 'CanTargetMissiles', as well
as a 'targetable' attribute for weaponFire. Weapons with the
'CanTargetMissiles' property can fire at projectiles that have
'targetable' set as true.
Note that in TSEDevices.h, we use one of the remaining 8 "spare bits" of `m_dwSpare2` instead of `m_fSpare5, m_fSpare6, m_fSpare7, m_fSpare8` for the `CanTargetMissiles` property. This is because pull request #13 uses those spare bits.
> Allow select weapons to fire upon certain missiles.

- Transcendence/TransCore/RPGShipBroker.xml
Two minor tweaks to rpgGetShipDetails
* Use short generic name for default reactor/drive - needed if we are called with a named ship e.g. "Volkov drive"
* Show armor count - so player can see number of armor segments in ship broker etc.
> rpgGetShipDetails

- Transcendence/TransCore/StdAutons.xml
- Now actually fixes the bug with not finding stations that can't attack by checking the same set of ships and stations after exploring one as it does when first issued the explore order.
- Using showMapLabel property excludes satellite stations such as Arcology segments and Sung defense turrets, slave quarters, and defense towers. It also excludes some stations in major clusters, especially near the Battle Arena. This may be undesireable, but shouldn't be a major problem because the main station in a cluster will be found if it wasn't set known at the start of the game. The galaxy map list avoids excluding these by checking whether the type normally shows a map label, but this doesn't seem to be possible in TLisp.
> Improve Explorer Auton

- Transcendence/TransCore/Mining.xml
- Transcendence/TransCore/RPGDockScreens.xml
- When taking ore without a miner's hold, only destroy ore if we haven't already.
- Loot Quantity screen can now have a custom desc passed in.
- "Loot" replaced with "Bring Aboard".
- Now fully translatable.
- Unreachable Default pane removed.
- Apparently unreachable Empty pane left... for now.
> Improve mined ore screens

- Transcendence/TransCore/RPGAutons.xml
Also, rpgDeployAutonFromItem now optionally accepts a messageID to display when deploying.
> Assign auton items with armor damage repairIDs for use by auton bay

- Mammoth/Include/TSEDeviceClassesImpl.h
- Mammoth/Include/TSEDevices.h
- Mammoth/TSE/CCyberDeckClass.cpp
- Mammoth/TSE/CShip.cpp
- Mammoth/TSE/CWeaponClass.cpp
- Mammoth/TSUI/CWeaponHUDCircular.cpp
- Mammoth/TSUI/CWeaponHUDDefault.cpp
This event enables us to have the UI display a custom amount of ammunition remaining. This displayed amount will not affect anything else that uses the ammo count (i.e. whether or not the weapon can fire, or any tlisp function that returns the amount of ammunition remaining), as it will not change the actual ammo count.
Using Nil as the return to GetAmmoCountToDisplay will use instead the ammo count that would have been used had the event not been called (if any).
> Added new event: GetAmmoCountToDisplay.

- Mammoth/TSUI/TSUICodeChain.cpp
This PR adds a new function (uiGetMousePos) that returns the cursor's X and Y coordinates as a list (x y), in pixels. The centre of the screen has the coordinates (0, 0), with X increasing as the cursor moves to the right and Y increasing as it moves upwards.
> Added uiGetMousePos

- Mammoth/Include/TSESpaceObjectsEnum.h
- Mammoth/Include/TSESpaceObjectsImpl.h
- Mammoth/TSE/CMissile.cpp
This PR comprises 2 changes. Firstly, all targetable missiles will
have lastFireTime equal to the current time, so that they will be
considered aggressors by AI point defenses (and so fired upon on sight).
Additionally, object finder classes will no longer consider "unreal"
objects, so that AI ships may avoid targeting missiles that are currently
fading out (since those objects are not considered 'destroyed' by the
engine).
> Improve AI gun targeting for targetable missiles.

- Mammoth/Include/TSEItems.h
- Mammoth/TSE/CCExtensions.cpp
- Mammoth/TSE/CItem.cpp
- Transcendence/TransCore/RPGAutons.xml
- Transcendence/TransCore/RPGWingmen.xml
- Transcendence/TransCore/StdAutons.xml
Fixes:
[Setting an item's 'installed property to Nil doesn't make it identical to the uninstalled version](https://ministry.kronosaur.com/record.hexm?id=88531)
At least, for the case of itmSetProperty. Cases where actual items are created or changed, like objAddItem and objSetItemProperty already seem to handle it properly. There may be some additional places where we should remove the extra data from items if it's blank, but I'm not aware of it causing any other problems in-game, so I didn't look too hard.
> Make modified autons in stock configuration coalesce with unmodified

- Mammoth/TSE/CWeaponClass.cpp
> GetAmmoCountToDisplay should not show number on HUD if event returns Nil

- Mammoth/TSE/CWeaponClass.cpp
Presently, when a gun with `burstTracksTargets` is aiming at a target that
is destroyed during the burst, the gun continues the burst at that given
firing angle regardless of the ship's orientation (even if the firing
angle is outside the gun's fire arc). This fix makes the gun fire down the
default fire angle if the target is destroyed during the burst.
> Fix `burstTracksTargets` repeating weapon aim when target destroyed during burst

- Mammoth/TSE/CCExtensions.cpp
This is done by changing the linked fire options to 'Always' immediately
before firing, then changing it back to the original linked fire setting
immediately after firing.
> Make `ObjFireWeapon` independent of ship linked fire options

- Mammoth/TSE/CWeaponClass.cpp
- Mammoth/TSE/TargetListImpl.h
Classes `targetableMissile` and `missile` are treated by the engine as separate and different classes when guns are checking what objects they can target. In addition, the code never assigned the class of `targetableMissile` to any object. This change fixes this problem by assigning the `targetableMissile` target category to targetable missiles, and enabling any gun that can target `missiles` to target `targetableMissiles` as well.
> Fix guns not shooting at targetable missiles

- Mammoth/Include/TSEDeviceClassesImpl.h
- Mammoth/TSE/CShieldClass.cpp
This PR adds two new features for shield hit effects.
The first involves `flashEffect`s, which can be defined using either the `<FlashEffect>` tag or the `FlashEffect` field just like current `hitEffect`s. The main difference is that these are generated at the ship position, rather than hit position.
The second involves using painters for shield hit effects. This enables us to use TLisp to procedurally generate shield hit effects based on certain variables, e.g. damage of incoming fire, remaining shield HP, etc.
> Enable "flash" shield effects, as well as TLisp for procedural shield hit effects

- Mammoth/Include/TSE.h
- Mammoth/Include/TSEArmor.h
- Mammoth/Include/TSEShipClass.h
- Mammoth/Include/TSESpaceObjectsImpl.h
- Mammoth/Include/TSEStationType.h
- Mammoth/Include/TSEUtil.h
- Mammoth/Include/TSEVersions.h
- Mammoth/Include/TSEWeaponFireDesc.h
- Mammoth/TSE/CArmorClass.cpp
- Mammoth/TSE/CCExtensions.cpp
- Mammoth/TSE/CHullDesc.cpp
- Mammoth/TSE/CPerceptionCalc.cpp
- Mammoth/TSE/CShip.cpp
- Mammoth/TSE/CSpaceObject.cpp
- Mammoth/TSE/CStationType.cpp
- Mammoth/TSE/CWeaponFireDesc.cpp
- Mammoth/TSUI/CReactorHUDCircular.cpp
2 major changes: increase perception/stealth dynamic range to +-128, and enable
intrinsic stealth bonuses/penalties on ship hulls.
Note regarding new stealth/perception detection range:
The same formula is used for perception/stealth as before, so most values
should stay the same albeit with slight differences since they are now
calculated mathematically. The one significant difference is that if
perception = stealth + 4, detection range is 210 rather than 250
(perception = stealth + 5 gives detection range of 250).
> Stealth and perception enhancements

- Transcendence/TransCore/CommonwealthFleet.xml
- Transcendence/TransCore/CommonwealthVolunteerMission02.xml
- Transcendence/TransCore/CorporateAutonDealer.xml
- Transcendence/TransCore/Psych01.xml
- Transcendence/TransCore/RPGDockServices.xml
- Transcendence/TransCore/StdWeapons.xml
Fixes for auton dealer (see [Auton repair and salvage bugs](https://ministry.kronosaur.com/record.hexm?id=96574))
* Consider `hullDamage == 0` as undamaged and do not display "Hull: 0% integrity"
* Add missing `autonConfig` definition when repairing hull so custom auton configuration is not lost
Add `showChargesInUseMenu="true"` to disposable launchers so player can see remaining missiles in [U]se menu
Add missing `replaceItem` when replacing shields so player can compare old / new devices (as already done for misc devices and weapons)
> Misc fixes for 1.9b4

- Mammoth/TSE/CContinuousBeam.cpp
Currently, the `continuousBeam` search algorithm loops through all objects in an A x A bounding box, where A is the length of a single beam segment. Since A can be very large, this can involve a lot of objects that are unnecessarily looped through. This optimization breaks it down into a series of B x B bounding boxes, where B << A. By doing this, we avoid looping through a lot of objects that we may have otherwise looped through, resulting in a massive performance increase when using hitscan beam weapons with very long ranges.
Demonstration video: https://streamable.com/511kjz
> Performance optimization for hitscan beams

- Mammoth/TSE/AIManeuvers.cpp
- Mammoth/TSE/ShipAIImpl.h
Certain IA ships with wide arc broadside guns and forward firing guns with narrow arcs prefer to keep their broadside guns pointed towards the enemy instead of bringing their forward guns to bear. This PR attempts to deprioritize guns that are on target and that have wide firing arcs, in an attempt to remedy this.
> Prioritize guns with smaller firing arcs when trying to align guns on target

- Mammoth/TSE/CSystemSpacePainter.cpp
When hiding the bars on the Intro Screen, the top edge of the space background is attached to the bottom edge of the top bar.
> Intro Screen: detach space background from top bar

- Mammoth/Include/TSESpaceObjectsImpl.h
- Mammoth/TSUI/CArmorHUDRingSegments.cpp
- Mammoth/TSUI/HUDImpl.h
New fields added for the HUD are `hullColor` which denotes the color of the hull bubble indicator (in the same format as `armorColor` and `shieldColor`), and `noArmorHPLabel` which removes HP percentage labels on armor segments (useful for capships with many armor segments).
Video to show how it looks: https://streamable.com/0xn030
> Add hull integrity display for player ship on HUD; use actual ship armour spans for HUD armour display

- Mammoth/TSE/CArmorClass.cpp
- Transcendence/TransCore/StdArmor.xml
The balance algorithm now looks for a mass class named "maximum". This is defined in the xml as 1000000kg. Anything above it will not return valid balance values.
Not specifying it results in using the legacy maximum of 16000kg.
Intended to address, which came up while working on an expanded universe project.
https://ministry.kronosaur.com/record.hexm?id=103768
> fix: 103768: allow balance computations up to an xml-specified maximum

- Mammoth/Include/TSE.h
- Mammoth/Include/TSEDeviceClassesImpl.h
- Mammoth/Include/TSEDevices.h
- Mammoth/TSE/CAutoDefenseClass.cpp
- Mammoth/TSE/CShip.cpp
- Mammoth/TSE/CSpaceObject.cpp
ticket: https://ministry.kronosaur.com/record.hexm?id=103609
autodefense devices automatically acquire new targets when their current target is destroyed, autodefense devices now wont pick targets that are flying away from them but may target them briefly as they pass by, autodefense devices get a small buff to targeting range when mounted on very large ships (ex, a CSC) unless using criteria-based distance (ex, "mEA NN:20")
> fix: 103609: autodefense device improvements

- Transcendence/TransCore/StdShields.xml
chore: 103788: update superconducting coil to use an attribute instead of a fixed UNID
> chore: 103788: update superconducting coil to use an attribute instead of a fixed UNID

- Mammoth/TSE/CEngineOptions.cpp
fix: 104101: correctly use DestTable instead of only overwriting m_ArmorDamageAdj regardless if shields or armor are being overwritten
> fix: 104101: correctly use DestTable instead of only overwriting m_ArmorDamageAdj regardless if shields or armor are being overwritten

- Transcendence/TransCore/BattleArena.xml
- Transcendence/TransCore/BattleArenaChallenger.xml
- Transcendence/TransCore/BattleArenaFight.xml
- Transcendence/TransCore/BattleArenaMelee.xml
- Transcendence/TransCore/CMPT_SOTPSoundtrackUNIDsLibrary.xml
- Transcendence/TransCore/HumanSpaceVol01.xml
- Transcendence/TransCore/StarsOfThePilgrim.xml
- Transcendence/TransCore/Transcendence.xml
Note: it needs to load before humanspacevol01.xml in the transcendence.exe library order so that the arena modules can use it.
> chore: 104105: add UNID library for soundtrack.

- Mammoth/TSE/CShieldClass.cpp
Display in seconds rather than relative % to a mysterious hidden number
> feat: 104233: add a better ui for regen delay (display in actual seconds)

- Mammoth/TSE/CSovereign.cpp
[ticket 104380](https://ministry.kronosaur.com/record.hexm?id=104380) 
Added an if block around code that checked disposition of sovereign to check if compared sovereign was null.
> fix: 104380: fixing null sovereign causing null pointer crash

- Mammoth/Include/TSESpaceObjectsImpl.h
- Mammoth/TSE/CContinuousBeam.cpp
Follow on from #156 - this should resolve all the visual artefacts e.g. beam end flickering in slow motion, or beam twisting/rotating etc.
> Further work on continuous beam

- Alchemy/CodeChain/DefPrimitives.h
- Alchemy/CodeChain/Functions.cpp
- Alchemy/CodeChain/Functions.h
- Alchemy/Include/CodeChain.h
- Alchemy/Include/KernelString.h
- Alchemy/Kernel/CString.cpp
- Mammoth/Include/TSEVersions.h
https://ministry.kronosaur.com/record.hexm?id=104332
Also includes the !=== operator
Important notes:
1. This function is being treated as performance sensitive code due to planned use in some libraries such as TAI. It will NOT have the safety of an API version check, so ensure that you bump your API version if you use this function.
2. we can now test for an explicit atomic Nil. This is crucial for code that needs to test if it has been passed a real list it can operate in-place on, or a Nil, which it cannot.
3. This function is case sensitive. It treats "A" != "a".
4. explicit gt/lt/gte/lte versions are not included in this PR, but may be something we want to look at in the future for string comparisons as the case sensitive handling can work with that. Note: it would treat "A" < "a", …
> Feature/104332 === operator

- Alchemy/CodeChain/Functions.cpp
- Transcendence/Game/TLisp/ListUnitTest.tlisp
This issue is causing shipbrokers to not work, since the improved shipbroker code deliberately makes calls to subset that are usually out of range.
> fix: 104459: fix out of bounds condition when using lists (technically only impacted subset)
